ci(default-bare): requirements-dev.txt, idempotence fail or pass

diff --git a/.github/workflows/default-bare.yml b/.github/workflows/default-bare.yml
--- a/.github/workflows/default-bare.yml
+++ b/.github/workflows/default-bare.yml
@@ -68,6 +68,7 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/$PYINFRA_DIR
           [ -f requirements.txt ] && pip install -r requirements.txt
+          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt
           pip3 show pyinfra
       - name: Environment
         run: |
@@ -82,7 +83,8 @@ jobs:
           PY_COLORS: '1'
       - name: Idempotency run
         run: |
-          cd $GITHUB_WORKSPACE/$PYINFRA_DIR && pyinfra @local nanokvm_deploy.py -y
+          cd $GITHUB_WORKSPACE/$PYINFRA_DIR && pyinfra @local nanokvm_deploy.py -y | tee /tmp/idempotency.log
+          cat /tmp/idempotency.log | grep -qE 'Success|Error'  && (echo 'Idempotence test: fail' && exit 1)  || (echo 'Idempotence test: pass' && cat /tmp/idempotency.log && exit 0)
         env:
           PY_COLORS: '1'
       - name: Verify
